[project]
name = "emerge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "kumarswamynaidu09@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "pillow>=12.3.0",
    "questionary>=2.1.1",
    "rich>=15.0.0",
    "typer>=0.27.1",
]

[project.scripts]
emerge = "emerge:app"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
